### ISSUE TITLE
 /sys/devices/platform/pwm-fan/hwmon/hwmon0/automatic: Permission denied

### ISSUE THREAD

**Issue by empierre** [f1vefour/odroid-xu4-fan-control#3]
Hello,

  on a fresh install on a Linux odroid 4.14.5-92 I have this : 

./odroid-xu4-fan-control.sh: line 29: /sys/devices/platform/pwm-fan/hwmon/hwmon0/automatic: Permission denied

**Comment by f1vefour** [comment]
You need to run the script with sudo or as root.

**Comment by empierre** [comment]
does not work, seems related to the kernel version, which is the odroid official one, odroid asked me to go to a dev one to have this value ...

odroid@odroid:~$ ls -l /sys/devices/platform/pwm-fan/hwmon/hwmon0/
device/    name       power/     subsystem/
fan_speed  of_node/   pwm1       uevent

**Comment by f1vefour** [comment]
It shouldn't be a dev kernel, I'm running the latest available kernel in Hardkernel repository.

run

- sudo apt update
- sudo apt upgrade
- sudo apt dist-upgrade

**Comment by empierre** [comment]
me too:

Linux odroid 4.14.5-92 #1 SMP PREEMPT Mon Dec 11 15:48:15 UTC 2017 armv7l armv7l armv7l GNU/Linux

"As described in the WiKi page, the kernel version must be higher than 4.14.32.
Update the system software first."

https://forum.odroid.com/viewtopic.php?f=52&t=16308&p=222011#p222011

**Comment by f1vefour** [comment]
Your kernel is not updated. It should be 4.14.37+

The forum topic you linked does not exist, please check it.

**Comment by empierre** [comment]
yes now I have the right kernel ! with time and patience, thanks!

**Comment by f1vefour** [comment]
I'm glad you got it working ;)
