### ISSUE TITLE
Installation for systemd

### ISSUE THREAD

**Issue by ubunonymount** [f1vefour/odroid-xu4-fan-control#4]
Hallo,

unfortunately I'm very new to linux and didn't get the installation part running.
I found out, that my system is not using init.d, but system.d. So I'm not really sure what to do, to get the installtion part running?

`cd /etc/init.d/` 
`#adjust to correct, absolute path below`
`sudo ln -s ~/odroid-xu4-fan-control /etc/init.d/odroid-fan-controller`
`sudo update-rc.d odroid-fan-controller defaults`

> do I have to change the location to `/usr/lib/systemd/system/` ?

So, I think linking doesn't work for system.d, or does it? 
Do you know how to do?
Thank you.

**Comment by f1vefour** [comment]
I'm not running systemd, I will have to research what to do.

**Comment by ubunonymount** [comment]
Yesterday I was very busy finding a solution for that, but it still doesn't work.
I tried to write a `.service` file called `odroidxu4fancontrol.service` for systemd 
_______________________________________________________________
`[Unit]`
`Description=Enable service provided by daemon.`
`After=remote-fs.target`

`[Service]`
`ExecStart=/home/odroid/odroid-xu4-fan-control/odroid-xu4-fan-control.sh`
`Type=forking`
`PIDFile=/var/run/odroidxu4fancontrol.pid`

`[Install]`
`WantedBy=multi-user.target`
_______________________________________________________________
and saved it in `/usr/lib/systemd/system` and then run:

`>$ sudo systemctl restart odroidxu4fancontrol.service`

But it was hanging very long and when it responded the answer was:


`Job for odroidxu4fancontrol.service failed because a timeout was exceeded.
See "systemctl status odroidxu4fancontrol.service" and "journalctl -xe" for details.`

_______________________________________________________________

So I tried `systemctl status odroidxu4fancontrol.service` and it said: 


_**\*** odroidxu4fancontrol.service - Enable service provided by daemon._
   _Loaded: loaded (/usr/lib/systemd/system/odroidxu4fancontrol.service; enabled; vendor preset: disabled)_
   _Active: **failed** (Result: timeout) since Sun 2018-06-03 14:02:53 UTC; 3min 8s ago_
  _Process: 4360 ExecStart=/home/odroid/odroid-xu4-fan-control/odroid-xu4-fan-control.sh (code=killed, signal=TERM)_

_Jun 03 14:01:23 alarm systemd[1]: Starting Enable service provided by daemon...._
_Jun 03 14:01:23 alarm odroid-xu4-fan-control.sh[4360]: fan control started. Current max temp: 62000_
_Jun 03 14:01:23 alarm odroid-xu4-fan-control.sh[4360]: For more logs see:_
_Jun 03 14:01:23 alarm odroid-xu4-fan-control.sh[4360]: sudo tail -f /var/log/syslog_
_Jun 03 14:02:53 alarm systemd[1]: odroidxu4fancontrol.service: Start operation timed out. Terminating._
_Jun 03 14:02:53 alarm systemd[1]: odroidxu4fancontrol.service: Failed with result 'timeout'._
_Jun 03 14:02:53 alarm systemd[1]: **Failed to start Enable service provided by daemon..**_

_______________________________________________________________

Maybe someone is familiar with systemd and can help me?

**Comment by SP-937-215** [comment]
Why don't you simplify your service file like this ?
```
[Unit]
Description=Simple shell script to better control Odroid XU4 fan

[Service]
ExecStart=/usr/sbin/odroid-xu4-fan-control.sh

[Install]
WantedBy=multi-user.target
```

**Comment by f1vefour** [comment]
@QCMR Looks fine to me, does it work?

**Comment by ubunonymount** [comment]
@QCMR Thank you very much! I think my approach was a bit to complexed although the answer is very simple. I'm very new to linux and systemd.
@f1vefour Yes, it seems to work now.

So, what I did was just to put your `odroid-xu4-fan-control.sh` file into `/usr/sbin/` and then write a `.service` script in `/usr/lib/systemd/system` with QCMRs content. After all files are saved I run the command `sudo systemctl enable odroidxu4fancontrol.service` and `sudo systemctl restart odroidxu4fancontrol.service` and it works! To change temperature settings, I just edited `/usr/sbin/odroid-xu4-fan-control.sh` file.

But now I have some other problem. I don't know what caused it, but when my fan is quiet I hear a very noise high pitched beep tone, coming out from my odroid xu4. Do you have any idea what caused it?

**Comment by f1vefour** [comment]
What does this say when it's making that noise?

```
cat /sys/devices/platform/pwm-fan/hwmon/hwmon0/pwm1
```

**Comment by ubunonymount** [comment]
it just says:
`80`

**Comment by f1vefour** [comment]
Raise the **80's**  in the script to **100** 

Some fans won't start if the PWM value is too low.

**Comment by ubunonymount** [comment]
ahh, yes.
I think it works. But why is this beep gone now? What did the beep mean?
Thank you very much!

**Comment by f1vefour** [comment]
@ubunonymount When the fan doesn't have enough energy (enough PWM value) to make it spin up it makes that squeaking noise. If you would have spun the fan while it makes that noise it would have began spinning.

Nothing to worry about, as I said each XU4 fan is different and requires a different minimum PWM value to start. Never seen one require over 80 but as long as it's working.

**Comment by ubunonymount** [comment]
Ahh, okay, thank you very much!!! 👍

**Comment by SP-937-215** [comment]
Sorry, I was off.
Yes, it works and as I'm crazy and I live in a hot country I slighltly increased the number of levels to make the speed very linear.
Note to @ubunonymount, I don't have the squizzing noise because I replaced the original fan by a tiny Zalman + a copper heat sink

```
new_fan_speed=0
  if (( ${current_max_temp} >= 75000)); then
    new_fan_speed=255
  elif (( ${current_max_temp} >= 73000)); then
    new_fan_speed=234
  elif (( ${current_max_temp} >= 71000)); then
    new_fan_speed=214
  elif (( ${current_max_temp} >= 69000)); then
    new_fan_speed=193
  elif (( ${current_max_temp} >= 67000)); then
    new_fan_speed=173
  elif (( ${current_max_temp} >= 65000)); then
    new_fan_speed=153
  elif (( ${current_max_temp} >= 63000)); then
    new_fan_speed=132
  elif (( ${current_max_temp} >= 61000)); then
    new_fan_speed=112
  elif (( ${current_max_temp} >= 59000)); then
    new_fan_speed=91
  elif (( ${current_max_temp} >= 57000)); then
    new_fan_speed=71
  elif (( ${current_max_temp} >= 55000)); then
    new_fan_speed=51
  elif (( ${current_max_temp} >= 53000)); then
    new_fan_speed=30
  elif (( ${current_max_temp} >= 51000)); then
    new_fan_speed=10
  elif (( ${current_max_temp} >= 49000)); then
    new_fan_speed=0
  else
    new_fan_speed=0
  fi
```
